checkout/link_checkoutcom

- Cartridges/int_checkoutcom_sfra/cartridge/controllers/CheckoutServices.js
- Cartridges/int_checkoutcom_sfra/cartridge/scripts/helpers/ckoHelper.js
- Cartridges/int_checkoutcom_sfra/cartridge/static/default/js/apm.js
- Cartridges/int_checkoutcom_sfra/cartridge/static/default/js/applepay.js
- Cartridges/int_checkoutcom_sfra/cartridge/static/default/js/cardPayment.js
- Cartridges/int_checkoutcom_sfra/cartridge/static/default/js/checkoutcom.js
- Cartridges/int_checkoutcom_sfra/cartridge/static/default/js/googlepay.js
- Cartridges/int_checkoutcom_sfra/cartridge/templates/default/checkout/billing/paymentOptions.isml
Added a confirmation step after the payment forms.
> Updated the SFRA integration

- Cartridges/int_checkoutcom_sfra/cartridge/controllers/CKOSepa.js
- Cartridges/int_checkoutcom_sfra/cartridge/scripts/config/ckoApmConfig.js
- Cartridges/int_checkoutcom_sfra/cartridge/scripts/helpers/apmHelper.js
- Cartridges/int_checkoutcom_sfra/cartridge/scripts/helpers/ckoHelper.js
- Cartridges/int_checkoutcom_sfra/cartridge/static/default/css/sepa.css
- Cartridges/int_checkoutcom_sfra/cartridge/templates/default/checkout/billing/paymentOptions/forms/apm/sepa.isml
- Cartridges/int_checkoutcom_sfra/cartridge/templates/default/sepaForm.isml
I have created this branch based on the current version of upa-sfra-improvments as of today 8/June/2020. This branch include the fix for sepa and sofort. Thanks
> Upa sfra sepa sofort

- Cartridges/int_checkoutcom/cartridge/static/default/js/apm.js
Removed Klarna payment authorization button after click ECPINT-687
> Removed Klarna payment authorization button after click ECPINT-687

- Cartridges/int_checkoutcom/cartridge/scripts/config/ckoApmConfig.js
- Cartridges/int_checkoutcom/cartridge/static/default/js/apm.js
- Cartridges/int_checkoutcom/cartridge/templates/default/apm/boleto.isml
Hi David, the current boleto object is outdated, therefore i have applied the latest object format to sgjc. Please PR.
Thanks
> Fixed boleto request source object issue ECPINT-702

- Cartridges/int_checkoutcom/cartridge/scripts/helpers/ckoHelper.js
@david-fiaty-cko just made a small fix to fawry apm payment request object, by changing the products object in ckoHelper. Please help me review. Thanks
> Fix Fawry payment request object invalid issue, ECPINT-703

- Cartridges/int_checkoutcom_sfra/cartridge/controllers/PaymentInstruments.js
- copied PaymentInstruments.js from app_storefront_base
- modified lines #203 & #210 to create a CHECKOUTCOM_CARD payment method and not a CREDIT_CARD payment method
> ECPINT-1260-savedCards-not-visible-at-billing-BUG

- Cartridges/int_checkoutcom_sfra/cartridge/client/default/scss/apm/klarna.scss
> ECPINT-1060-klarna-logo-misplaced-BUG

- Cartridges/int_checkoutcom_sfra/cartridge/templates/default/checkout/billing/paymentOptions/forms/applePayForm.isml
- removed the custom button added in template
> ECPINT-1414-apple-pay-shows-twice

- Cartridges/int_checkoutcom_sfra/cartridge/controllers/CKOKlarna.js
- Cartridges/int_checkoutcom_sfra/cartridge/scripts/helpers/ckoHelper.js
- new function in ckoHelper which will return the shipping address from session
- function called for storing address in session
> ECPINT-1535-klarna-14-days-fails-BUG

- bin/Makefile.js
- bin/test-functional-docker.sh
> ECPINT-1601-add-bin-folder

- Cartridges/int_checkoutcom_sfra/cartridge/client/default/js/cardPayment.js
- modified logic so that card number validation goes through cleave
> ECPINT-1562-cc-validation-BUG

- Cartridges/int_checkoutcom_sfra/cartridge/static/default/js/cardPayment.js
- modified logic for form invalidation
> reviewed-ECPINT-1629-submit-pressed-twice-BUG

- Cartridges/int_checkoutcom_sfra/cartridge/static/default/css/apm/klarna.css
> reviewed-ECPINT-1631-klarna-logo-misplaced

- Cartridges/int_checkoutcom_sfra/cartridge/static/default/js/applepay.js
- added code to hide the apple-pay tab if ApplePaySession is not available
> reviewed-ECPINT-1627-applepay-visible-anytime-BUG

- Cartridges/int_checkoutcom_sfra/cartridge/scripts/helpers/ckoHelper.js
- changed logic to check for that property in correct location
> reviewed-ECPINT-1665-sofort-payment-fails-BUG

- Cartridges/int_checkoutcom/cartridge/static/default/js/applepay.js
- added code to hide applepay option if condition is not met
> reviewed-ECPINT-1679-SGJC-applepay-visible-anytime-BUG

- Cartridges/int_checkoutcom/cartridge/static/default/css/apm.css
- modified css to center the image
> reviewed-ECPINT-1680-SGJC-klarna-logo-misplaced-BUG

- Cartridges/int_checkoutcom/cartridge/scripts/payment/processor/CHECKOUTCOM_CARD.js
- added expiration date validation
> reviewed ECPINT-1681 SGJC no CC number validation BUG

- metadata/meta/system-object-definitions.xml
- package-lock.json
- package.json
- updated version number in files
> reviewed ECPINT-1685 update version

- metadata/services.xml
> added services.xml

- Cartridges/int_checkoutcom_sfra/cartridge/scripts/helpers/ckoHelper.js
- Cartridges/int_checkoutcom_sfra/cartridge/scripts/helpers/sensitiveDataHelper.js
- moved sensitive data code to its own file
- updated ckoHelper
> - moved sensitive data logic

- Cartridges/int_checkoutcom/cartridge/scripts/helpers/ckoHelper.js
- Cartridges/int_checkoutcom/cartridge/scripts/helpers/sensitiveDataHelper.js
- moved sensitive data logic to its own file
- updated ckoHelper.js
> moved sensitive data logic

- Cartridges/int_checkoutcom_sfra/cartridge/static/default/css/apm/klarna.css
- Cartridges/int_checkoutcom_sfra/cartridge/static/default/js/apm/klarna.js
- added classes and removed inline css
- added the css to its own file
> modified inline css

- 20.3.0/Cartridges/int_checkoutcom/cartridge/scripts/helpers/eventsHelper.js
- 20.3.0/Cartridges/int_checkoutcom_sfra/cartridge/scripts/helpers/eventsHelper.js
- added function to set the payment status based on the amountPaid
- added calls to that function for void,refund,capture scenarios
> added functionality to set the payment status

- 20.3.0/Cartridges/int_checkoutcom_sfra/cartridge/scripts/helpers/eventsHelper.js
- 20.3.0/Cartridges/int_checkoutcom_sfra/cartridge/scripts/helpers/transactionHelper.js
- changed how we get the payment method name
> updated payment method name

- 20.3.0/Cartridges/int_checkoutcom/cartridge/scripts/helpers/eventsHelper.js
- 20.3.0/Cartridges/int_checkoutcom/cartridge/scripts/helpers/transactionHelper.js
- changed how we get the payment method id
> updated payment method

- 20.2.0/Cartridges/int_checkoutcom/cartridge/scripts/helpers/eventsHelper.js
- 20.2.0/Cartridges/int_checkoutcom_sfra/cartridge/scripts/helpers/eventsHelper.js
- added function to set the payment status based on the amount paid
- added calls to that function on capture, refund and void
> payment status logic

- Cartridges/int_checkoutcom/cartridge/controllers/CKOGooglePay.js
- Cartridges/int_checkoutcom_sfra/cartridge/controllers/CKOGooglePay.js
- fixed an issue with bussiness name while using google pay
> google pay name issue

- Cartridges/bm_checkoutcom/cartridge/scripts/helpers/CKOHelper.js
- Cartridges/int_checkoutcom/cartridge/scripts/helpers/ckoHelper.js
- Cartridges/int_checkoutcom_sfra/cartridge/scripts/helpers/ckoHelper.js
- modified custom pref getter function
> ECPINT-2541

- Cartridges/bm_checkoutcom/cartridge/static/default/js/core/actions.js
- fixed issue where refunded amount is 100 times less
> ECPINT-2764-refund

- Cartridges/bm_checkoutcom/cartridge/scripts/helpers/CKOHelper.js
- Cartridges/bm_checkoutcom/cartridge/static/default/js/core/actions.js
- Cartridges/bm_checkoutcom/cartridge/static/default/js/core/list.js
- changed logic to support multiple refunds
> ECPINT-2783-BM-partial-refunds

- Cartridges/int_checkoutcom/cartridge/scripts/helpers/googlePayHelper.js
- Cartridges/int_checkoutcom/cartridge/scripts/payment/processor/CHECKOUTCOM_GOOGLE_PAY.js
**Notes**
This PR aims to fix google pay functionality
- stringified request data for Google Pay
- updated google pay processor to create correct payment instrument
> ECPINT-2789-SG-google-pay

- Cartridges/int_checkoutcom_sfra/cartridge/scripts/helpers/ckoHelper.js
- Cartridges/int_checkoutcom_sfra/cartridge/scripts/helpers/googlePayHelper.js
- Cartridges/int_checkoutcom_sfra/cartridge/scripts/hooks/payment/processor/CHECKOUTCOM_GOOGLE_PAY.js
- Cartridges/int_checkoutcom_sfra/cartridge/scripts/hooks/payment/processor/CHECKOUTCOM_GOOGLE_PAY_form_processor.js
- Cartridges/int_checkoutcom_sfra/cartridge/static/default/js/googlepay.js
**Notes**
This PR aims to fix google pay functionality on SFRA
- modified form_processor to respect actual function call
- modified google_pay processor to create correct payment instrument and remove data once not needed
- changed frontend logic to automatically progress checkout process
- added risk flag to api call
> ECPINT-2788-google-pay-fixes

- Cartridges/int_checkoutcom_sfra/cartridge/scripts/hooks/payment/processor/CHECKOUTCOM_APPLE_PAY.js
- updated apple pay to create correct payment instrument
> ECPINT-2790-SFRA-apple-pay

- Cartridges/int_checkoutcom/cartridge/scripts/payment/processor/CHECKOUTCOM_APPLE_PAY.js
- updated payment logic to create correct payment instrument
> ECPINT-2793-SFRA-apple-pay

- Cartridges/int_checkoutcom/cartridge/static/default/js/applepay.js
- Cartridges/int_checkoutcom_sfra/cartridge/static/default/js/applepay.js
- added check if country is SA, mada is included as supported network
> ECPINT-2677-include-MADA

- Cartridges/int_checkoutcom/cartridge/forms/default/cardPaymentForm.xml
- updated the length for the CC owner name
> ECPINT-2746-update-cc-owner-length

- Cartridges/int_checkoutcom_sfra/cartridge/forms/default/creditCard.xml
- updated the length for the CC owner name
> ECPINT-2747-updated-cc-owner-length

- Cartridges/int_checkoutcom_sfra/cartridge/templates/default/checkout/billing/paymentOptions/contents/apmContent.isml
- added correct class to oxxo div
> ECPINT-2777-oxxo-always-displayed

- Cartridges/int_checkoutcom_sfra/cartridge/scripts/config/ckoApmConfig.js
- Cartridges/int_checkoutcom_sfra/cartridge/templates/default/checkout/billing/forms/apms/oxxo.isml
- Cartridges/int_checkoutcom_sfra/cartridge/templates/resources/cko.properties
- corrected oxxo displayed text
- fixed authorization function
> ECPINT-2785-oxxo-label-change

- metadata/meta/system-object-definitions.xml
- package.json
> ECPINT-2745-updated-version-metadata

- Cartridges/int_checkoutcom/cartridge/forms/default/cardPaymentForm.xml
- Cartridges/int_checkoutcom/cartridge/static/default/js/cardPayment.js
- added max length to the card owner field
> ECPINT-2746-CC-name-maxLength
